from .acre import AcreLegisScraper
from .alagoas import AlagoasSefazScraper
from .amapa import AmapaAlapScraper
from .amazonas import LegislaAMScraper
from .bahia import BahiaLegislaScraper
from .ceara import CearaAleceScraper
from .distrito_federal import DFSinjScraper
from .espirito_santo import ESAlesScraper
from .goias import LegislaGoias
from .maranhao import MaranhaoAlemaScraper
from .mato_grosso_do_sul import MSAlemsScraper
from .mato_grosso import MTAlmtScraper
from .minas_gerais import MGAlmgScraper
from .para import ParaAlepaScraper
from .paraiba import ParaibaAlpbScraper
from .parana import ParanaCVScraper
from .sao_paulo import SaoPauloAlespScraper
from .rio_de_janeiro import RJAlerjScraper
from .rio_grande_do_norte import RNAlrnScraper
from .rio_grande_do_sul import RSAlrsScraper
